FROM php:7.3-apache

RUN apt-get update -y

# Evitar CouldNotDetermineServerName
# https://cwiki.apache.org/confluence/display/HTTPD/CouldNotDetermineServerName
#echo "ServerName localhost" >> /etc/apache2/apache2.conf

